spring:
  application:
  name: demo
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234

  jackson:
    time-zone: UTC



  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true

  flyway:
    locations: classpath:/db/migration
    baselineOnMigrate: true
    check-location: true
    enabled: true